version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Podfile
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
  db:
    image: docker.io/library/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data